### ISSUE TITLE
Add option to view past events

### ISSUE THREAD

**Issue by sudobob** [nova-labs/wild_apricot_python_flask_utils#1]
https://wautils.nova-labs.org/events only shows events in the future.
Add an option to show events in the past
https://github.com/nova-labs/wild_apricot_python_flask_utils/blob/master/static/wautils.js#L1167

**Comment by sudobob** [comment]
@csexton if this is done feel free to close.

**Comment by csexton** [comment]
![CleanShot 2021-04-15 at 12 20 53@2x](https://user-images.githubusercontent.com/16963/114903815-2ba16080-9de5-11eb-95a3-54595dc65607.png)

It is done! But I can only comment on this issue, don't have the super powers needed to close.

**Comment by sudobob** [comment]
Try again closing.

**Comment by csexton** [comment]
![I have the power](https://media4.giphy.com/media/BdAn5S0xigpO/giphy.gif)
